# Generated by Django 5.1.7 on 2025-03-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MetaLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, '1º Mês'), (2, '2º Mês'), (3, '3º Mês'), (4, '4º Mês'), (5, '5º Mês'), (6, '6º Mês'), (7, '7º Mês'), (8, '8º Mês'), (9, '9º Mês'), (10, '10º Mês'), (11, '11º Mês'), (12, '12º Mês')])),
                ('ano', models.IntegerField()),
                ('quantidade_meta', models.IntegerField()),
                ('livros_concluidos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano_publicacao', models.IntegerField()),
                ('numero_capitulos', models.IntegerField()),
                ('nota', models.IntegerField(choices=[(1, '1 Estrela(s)'), (2, '2 Estrela(s)'), (3, '3 Estrela(s)'), (4, '4 Estrela(s)'), (5, '5 Estrela(s)')])),
                ('review', models.TextField(blank=True, null=True)),
                ('estante', models.CharField(choices=[('na_estante', 'Na Estante'), ('lista', 'Lista'), ('lidos', 'Lidos'), ('lendo', 'Lendo')], default='na_estante', max_length=20)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('favorito', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leitura.genero')),
            ],
        ),
    ]
