# Generated by Django 5.1.7 on 2025-03-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0002_livro_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='favorito',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='livro',
            name='nota',
            field=models.IntegerField(blank=True, choices=[(1, '1 estrelas'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')], null=True),
        ),
    ]
