# Generated by Django 5.1.7 on 2025-03-07 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0003_alter_livro_favorito_alter_livro_genero_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
